- name: Encrypt username/password
  docker_container:
    name: htpasswd
    image: registry:2
    command: /usr/bin/htpasswd -Bbn "{{ item.username }}" "{{ item.password }}"
    detach: false
  register: htpasswdOutput

- name: get output
  shell: cat "{{ansible_docker_container.LogPath}}"
  become: true
  register: output

- set_fact:
    line: "{{output.stdout_lines[-2]}}"

- name: Create file, if it does not exist
  file:
    name: "{{ registry_auth_path }}/{{ registry_auth_file }}"
    state: touch

- name: Remove user from password file, if exists
  lineinfile:
    dest: "{{ registry_auth_path }}/{{ registry_auth_file }}"
    regexp: '^{{ item.username }}'
    state: absent 

- name: Add user to password file
  lineinfile:
    dest: "{{ registry_auth_path }}/{{ registry_auth_file }}"
    line: "{{ line.log | replace('\n', '') }}"
